name: deploy

on:
  push:
    branches: [main]
  repository_dispatch:
    types: deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: cp ./src/config.devnet.tsx ./src/config.tsx
      - run: npm install
      - run: npm run build
        env:
          CI: false
      - uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: production

